Merge de la branche originale

diff --git a/Makefile.rules b/Makefile.rules
--- a/Makefile.rules
+++ b/Makefile.rules
@@ -37,14 +37,14 @@ $(NAME): $(objs) $(extra_objs) $(ALLDEP)
 ifeq (,$(FASTER))
 	@echo "Linking $(NAME)"
 endif
-	$(Q)$(LD) $(LDFLAGS) $(objs) $(extra_objs) $(LIBS) -o $(NAME)
+	$(Q)$(LD) $(LDFLAGS) $(objs) $(extra_objs) $(LIBS) $(TWEAK_LIBS) -o $(NAME)
 
 
 main.o: main.c $(ALLDEP) $(NEWREVISION)
 ifeq (,$(FASTER))
 	@echo "Compiling $<"
 endif
-	$(Q)$(CC) $(CFLAGS) $(DEFS) -c $< -o $@
+	$(Q)$(CC) $(CFLAGS) $(DEFS) $(TWEAK_DEFS) -c $< -o $@
 
 .PHONY: all
 all: $(NAME) modules
@@ -170,19 +170,22 @@ proper realclean distclean: clean
 		fi ; \
 	done
 	-@if [ -d menuconfig ]; then $(MAKE) -C menuconfig proper; fi
-	-@if [ -d utils/opensipsunix ]; then $(MAKE) -C utils/opensipsunix proper; fi
 	-@if [ -d utils/db_berkeley ]; then $(MAKE) -C utils/db_berkeley proper; fi
 	-@if [ -d utils/db_oracle ]; then $(MAKE) -C utils/db_oracle proper; fi
 
-.PHONY: mantainer-clean
-mantainer-clean: distclean
+.PHONY: maintainer-clean
+maintainer-clean: distclean
 	-rm -f TAGS tags *.dbg .*.swp
 	-@for r in $(modules) "" ; do \
 		if [ -d "$$r" ]; then \
-			$(MAKE) -C $$r mantainer-clean; \
+			$(MAKE) -C $$r maintainer-clean; \
 		fi ; \
 	 done
-	-@if [ -d utils/opensipsunix ]; then $(MAKE) -C utils/opensipsunix mantainer-clean; fi
+
+.PHONY: mantainer-clean
+mantainer-clean:
+	@printf "\nERROR: Please use 'maintainer-clean', not 'mantainer-clean'\n\n" >&2
+	@false
 
 
 .PHONY: install_module_custom
@@ -195,7 +198,7 @@ TAGS:
 ifeq (,$(MAKECMDGOALS))
 -include $(depends)
 endif
-ifneq (,$(filter-out clean proper distclean realclean mantainer-clean TAGS \
+ifneq (,$(filter-out clean proper distclean realclean maintainer-clean TAGS \
 		test tar modules, $(MAKECMDGOALS)))
 -include $(depends)
 endif
